apiVersion: apps/v1
kind: Deployment
metadata:
  name: tel-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: tel
  replicas: 2
  template:
    metadata:
      labels:
        app: tel
    spec:
      containers:
        - name: tel-app
          image: bsdemon/tel-app:v1.0.1
          ports:
            - containerPort: 3000
